### PR TITLE
feat: add undeploy script

### PR DESCRIPTION
**Pull request by shaofeng66**

### CODE REVIEW

**Comment by half-life666** [comment]
Should we delete all other CR first? backupjob, backupplan, etc, then storage, cluster, delete tenant, deployment, namespace last.

**Comment by shaofeng66** [comment]
> Should we delete all other CR first? backupjob, backupplan, etc, then storage, cluster, delete tenant, deployment, namespace last.

When the namespace is deleted, these cr will also be deleted. This script is just to tear down the saas installation, by delete deployments first, we can ensure no problem when deleting other CRs, even if there is any code bug in controllers.

**Comment by half-life666** [comment]
> > Should we delete all other CR first? backupjob, backupplan, etc, then storage, cluster, delete tenant, deployment, namespace last.
> 
> When the namespace is deleted, these cr will also be deleted. This script is just to tear down the saas installation, by delete deployments first, we can ensure no problem when deleting other CRs, even if there is any code bug in controllers.

OK

**Review by jerry-jibu — APPROVED** [review]
it works for me, thanks.

**Pull request merged**
